version: '2'
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "28081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "28082:8080"
    volumes:
      - ./spec.yaml:/app.yaml
    environment:
      SWAGGER_JSON: /app.yaml